### ISSUE TITLE
Keyboard navigation has stopped working

### ISSUE THREAD

**Issue by erikshelley** [tonycpsu/bluesky-navigator#3]
Starting today I can no longer use arrow keys to move down through posts. Is it a Bluesky update or something on my end?

Firefox, Windows 11, Tampermonkey

**Comment by tonycpsu** [comment]
Up/down arrows still good for me on Firefox MacOS. Don't have a Windows environment handy to test.

**Comment by smnrg** [comment]
Same. Chromium, macOS. (posts not highlighted anymore either, also using hjkl etc. won't work.)

**Comment by tonycpsu** [comment]
Oops, see if the latest update fixes it.

**Comment by smnrg** [comment]
Still won't work, just updated.

Some pointers:

Stray forward slash on line 343:
/ return { ...defaultState, ...savedState };
Should be:
return { ...defaultState, ...savedState };

Typo in CONFIG_FIELDS object:
'threadIndicato Color' -> 'threadIndicator Color'

Incomplete handleItemKey function ending:
else if (event.key == ".") {
// toggle read/unread
this.markItemRead(this.index,
Needs second parameter and closing brace.

Some template literals using single quotes instead of backticks:
'div[aria-label^='Context menu backdrop']' -> div[aria-label^='Context menu backdrop']

**Comment by tonycpsu** [comment]
🤦 whoops, fixed the stray slash and the typo in CONFIG_FIELDS. Try again?  🤞 

I actually don't see anything wrong with the other two -- I don't think the popup selector is used as a template string, just a jquery selector, and markItemRead takes null as the second parameter to toggle instead of setting true/false.

**Comment by smnrg** [comment]
All solved! ☺️🙏

**Comment by erikshelley** [comment]
Confirmed. It is working now.
